sudo: required
services: 
  - docker

before_install:
  - docker build -t wano19/docker-react -f Dockerfile.dev .

script:
  - docker run wano19/docker-react npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: ""
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "S3 bucket name"
  bucket_path: "docker-react"
  on:
    branch: master
  acess_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
